<?php
declare(strict_types=1);

// Dtone SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

DtoneUtility::setRegistrar(function (DtoneUtility $u): void {
    $u->clean = [DtoneClean::class, 'call'];
    $u->done = [DtoneDone::class, 'call'];
    $u->make_error = [DtoneMakeError::class, 'call'];
    $u->feature_add = [DtoneFeatureAdd::class, 'call'];
    $u->feature_hook = [DtoneFeatureHook::class, 'call'];
    $u->feature_init = [DtoneFeatureInit::class, 'call'];
    $u->fetcher = [DtoneFetcher::class, 'call'];
    $u->make_fetch_def = [DtoneMakeFetchDef::class, 'call'];
    $u->make_context = [DtoneMakeContext::class, 'call'];
    $u->make_options = [DtoneMakeOptions::class, 'call'];
    $u->make_request = [DtoneMakeRequest::class, 'call'];
    $u->make_response = [DtoneMakeResponse::class, 'call'];
    $u->make_result = [DtoneMakeResult::class, 'call'];
    $u->make_point = [DtoneMakePoint::class, 'call'];
    $u->make_spec = [DtoneMakeSpec::class, 'call'];
    $u->make_url = [DtoneMakeUrl::class, 'call'];
    $u->param = [DtoneParam::class, 'call'];
    $u->prepare_auth = [DtonePrepareAuth::class, 'call'];
    $u->prepare_body = [DtonePrepareBody::class, 'call'];
    $u->prepare_headers = [DtonePrepareHeaders::class, 'call'];
    $u->prepare_method = [DtonePrepareMethod::class, 'call'];
    $u->prepare_params = [DtonePrepareParams::class, 'call'];
    $u->prepare_path = [DtonePreparePath::class, 'call'];
    $u->prepare_query = [DtonePrepareQuery::class, 'call'];
    $u->graphql_body = [DtoneGraphql::class, 'body'];
    $u->graphql_errors = [DtoneGraphql::class, 'errors'];
    $u->result_basic = [DtoneResultBasic::class, 'call'];
    $u->result_body = [DtoneResultBody::class, 'call'];
    $u->result_headers = [DtoneResultHeaders::class, 'call'];
    $u->transform_request = [DtoneTransformRequest::class, 'call'];
    $u->transform_response = [DtoneTransformResponse::class, 'call'];
});
